Austin 26 multilingual support v2
TexasCodeEm/cse112-sp22-team6 pull request #53
Opened 2022-06-05 00:23 UTC by jinbest17

2022-06-05 00:49 UTC, hod002 reviewed
Tutorial page doesn't change languages and i icon can't be clicked when spanish is selected.

2022-06-05 01:17 UTC, kgeewhan requested changes
i button cannot be clicked when the language is Spanish

2022-06-05 22:04 UTC, Youngjun333 approved these changes

2022-06-06 04:04 UTC, jinbest17 commented on cypress/integration/main/backgrounds.spec.js
> +  it("Clicking first language", () => {
Good job on making reusable test cases which we can revamp if we add more languages in the future.

2022-06-06 04:04 UTC, jinbest17 commented on cypress/integration/main/countdown.spec.js
> +            .contains('Reset');
good styling fix

2022-06-06 04:04 UTC, jinbest17 commented on gulpfile.js
>  const TUT_JS_PATH =  'source/tutorial-scripts/*.js';
Might be a good idea to reduce the size of gulpfile in the future for better readability.

2022-06-06 04:04 UTC, jinbest17 commented on source/index.html
> -    <link rel="stylesheet" href="./styles/switchBackground.css">
This line deletes deprecated css reference.

2022-06-06 04:04 UTC, jinbest17 commented on source/scripts/accessibility.js
>  document.onkeydown = keyControls;
duplicate with line 13

2022-06-06 04:04 UTC, jinbest17 commented on source/scripts/util/graph.js
>  /* Graph Constants */
Might consider changing the comment here since we are not declaring them as constants anymore to accomodate the multilingual feature.

2022-06-06 04:04 UTC, jinbest17 commented on source/scripts/util/language.js
> +
Need to get rid of empty lines

2022-06-06 04:11 UTC, kgeewhan approved these changes

2022-06-07 07:30 UTC, merged